apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev

data:
  SPRING_PROFILES_ACTIVE: "dev"

  SPRING_DATASOURCE_URL: "jdbc:postgresql://dermaday-db.cdc82maymta7.ap-northeast-2.rds.amazonaws.com:5432/dermaday_dev"

  FRONTEND_BASE_URL: "https://www.dermaday.me"
  BACKEND_BASE_URL: "https://api-dev.dermaday.me"

  JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=65.0"