apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev

data:
  # Env. Profile
  SPRING_PROFILES_ACTIVE: "dev"

  # Database
  SPRING_DATASOURCE_URL: "jdbc:postgresql://dermaday-db.cdc82maymta7.ap-northeast-2.rds.amazonaws.com:5432/dermaday_dev?sslmode=require"

  # Application URLs
  FRONTEND_BASE_URL: "https://dermaday.me"
  BACKEND_BASE_URL: "https://api-dev.dermaday.me"
  CORS_ALLOWED_ORIGINS: "https://dermaday.me,https://www.dermaday.me,http://localhost:5173"

  # JWT
  JWT_ACCESS_TOKEN_TTL: "PT24H"

  # S3
  AWS_REGION: "ap-northeast-2"
  S3_BUCKET: "dermaday-bucket"
  S3_PRESIGNED_URL_TTL: "PT30M"

  # Firebase Cloud Messaging
  FIREBASE_PROJECT_ID: "dermaday-71877"
  GOOGLE_APPLICATION_CREDENTIALS: "/var/run/secrets/firebase/service-account.json"
  PUSH_ENABLED: "true"

  # JVM
  JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=65.0"

  # Kubernetes probes
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
