apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: production

data:
  # Env. Profile
  SPRING_PROFILES_ACTIVE: "production"

  # Database
  SPRING_DATASOURCE_URL: "jdbc:postgresql://dermaday-db.cdc82maymta7.ap-northeast-2.rds.amazonaws.com:5432/dermaday_production?sslmode=require"

  # Application URLs
  FRONTEND_BASE_URL: "https://dermaday.me"
  BACKEND_BASE_URL: "https://api.dermaday.me"
  CORS_ALLOWED_ORIGINS: "https://dermaday.me,https://www.dermaday.me,http://localhost:5173"

  # JWT
  JWT_ACCESS_TOKEN_TTL: "PT24H"

  # JVM
  JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=65.0"

  # Kubernetes probes
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
